In [10]:
import numpy as np
a_2 = np.arange(25).reshape(5,5)
a_1 = np.arange(25).reshape(5,5)
b = np.arange(5)
d = np.arange(6)
c = np.arange(8).reshape(4,2)
print(a_2)
print(a_2.T)
#print(b)
#print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [3]:
np.insert(b, 1,5)

array([0, 5, 1, 2, 3, 4])

In [4]:
np.einsum('i,j->ij', b, d)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20]])

In [5]:

arr= np.einsum('ii->i', np.einsum('i,j->ij', b, d))
print(arr)
np.sum(arr)

ValueError: dimensions in single operand for collapsing index 'i' don't match (5 != 6)

In [109]:
weights = np.random.random(size=(4,))
x = np.random.random(size=(4,))

print(x[:,np.newaxis])
print(weights[:,np.newaxis])


[[0.02752336]
 [0.79206228]
 [0.15086397]
 [0.51901309]]
[[0.55065992]
 [0.53569633]
 [0.3213682 ]
 [0.44289588]]


In [116]:
np.einsum('i,j->i', x, weights)

array([0.0509353 , 1.46580655, 0.27919193, 0.96049617])

In [9]:
lr = 0.25
delta_j = -0.2
weights = np.array([0.2,0.54,-0.2,-0.5-0.23,0.3])
z=lr * np.array([0.5,0.24,-0.42,-0.25-0.03,0.23]) * delta_j
print(z)
print(weights)

[-0.025  -0.012   0.021   0.014  -0.0115]
[ 0.2   0.54 -0.2  -0.73  0.3 ]


In [8]:
np.add(weights,z)

array([ 0.175 ,  0.528 , -0.179 , -0.716 ,  0.2885])