In [128]:
import numpy as np
a_2 = np.arange(25).reshape(5,5)
a_1 = np.arange(25).reshape(5,5)
b = np.arange(5)
d = np.arange(5)
c = np.arange(8).reshape(4,2)

print(b)
print(b)

[0 1 2 3 4]
[0 1 2 3 4]


In [130]:
b*b

array([ 0,  1,  4,  9, 16])

In [131]:
np.einsum('i,j->ij', b, d)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [127]:

arr= np.einsum('ii->i', np.einsum('i,j->ij', b, d))
print(arr)
np.sum(arr)

[ 0  1  4  9 16]


30

In [109]:
weights = np.random.random(size=(4,))
x = np.random.random(size=(4,))

print(x[:,np.newaxis])
print(weights[:,np.newaxis])


[[0.02752336]
 [0.79206228]
 [0.15086397]
 [0.51901309]]
[[0.55065992]
 [0.53569633]
 [0.3213682 ]
 [0.44289588]]


In [116]:
np.einsum('i,j->i', x, weights)

array([0.0509353 , 1.46580655, 0.27919193, 0.96049617])